dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.4.1  # https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20.sol
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.1'
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}